// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnTdU6feqEh2Z5SVdEjDH-LyRfJTNn2mM',
    appId: '1:550757275151:web:e93d13828eccd9c798757a',
    messagingSenderId: '550757275151',
    projectId: 'cw06-3f0c4',
    authDomain: 'cw06-3f0c4.firebaseapp.com',
    storageBucket: 'cw06-3f0c4.firebasestorage.app',
    measurementId: 'G-2YG0JX106M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_fG-bRTa8jShAa2MjwtS55Z-FkSnf4aI',
    appId: '1:550757275151:android:fc8da77a6e097a1698757a',
    messagingSenderId: '550757275151',
    projectId: 'cw06-3f0c4',
    storageBucket: 'cw06-3f0c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Nh82J7U2ba7HcYLJsVytYMT6wDy9GIQ',
    appId: '1:550757275151:ios:c9c8ad6678c4e82c98757a',
    messagingSenderId: '550757275151',
    projectId: 'cw06-3f0c4',
    storageBucket: 'cw06-3f0c4.firebasestorage.app',
    iosBundleId: 'com.example.cw06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Nh82J7U2ba7HcYLJsVytYMT6wDy9GIQ',
    appId: '1:550757275151:ios:c9c8ad6678c4e82c98757a',
    messagingSenderId: '550757275151',
    projectId: 'cw06-3f0c4',
    storageBucket: 'cw06-3f0c4.firebasestorage.app',
    iosBundleId: 'com.example.cw06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnTdU6feqEh2Z5SVdEjDH-LyRfJTNn2mM',
    appId: '1:550757275151:web:2d439a185486408098757a',
    messagingSenderId: '550757275151',
    projectId: 'cw06-3f0c4',
    authDomain: 'cw06-3f0c4.firebaseapp.com',
    storageBucket: 'cw06-3f0c4.firebasestorage.app',
    measurementId: 'G-HR6HWC5WH9',
  );
}
